### ISSUE TITLE
Solo пул

### ISSUE THREAD

**Issue by swrg59** [Konstantin35/open-ethereum-pool#1]
Добрый день! Подскажите, возможно ли сделать соло пул на базе open-ethereum-pool, посмотрел, у вас много разных версий, под разные монеты. Мб вы и соло сделаете?

**Comment by Simkas45** [comment]
пожалуйста поделитесь решением чтобы создавать соло полы на open ethereum pool, очень необходимо, буду очень благодарен, телеграмм:@simkas45
